name: "Install Rust Dependencies"
description: "install Rust dependencies"
inputs:
  additional-libs:
    required: false
    type: string
    default: libdbus-1-dev libssl-dev

outputs: {}
runs:
  using: "composite"
  steps:
    - name: "install required Rust dependencies"
      shell: bash
      run: |
        sudo apt update
        sudo apt install build-essential ${{ inputs.additional-libs }}
